### ISSUE TITLE
Header Responsive

### ISSUE THREAD

**Issue by WayOfTheKatana** [dineshdevelope/React-Portfolio#1]
Dinesh, Make sure to give enough white spaces throughout the sections. Bring down the tech stacks section out from the full viewport ratio.

**Comment by dineshdevelope** [comment]
Thank you for your suggestion. I’m currently working on the issue and will fix it soon. If you find any other issues, please let me know, and I will include them in future updates.

**Comment by WayOfTheKatana** [comment]
sure why not bro!
